name: user_repository
description: "Dart package which manages user data."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

  # Firebase
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
