name: post_repository
description: "Dart package which manages post."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  uuid: ^4.5.1

  # Firebase
  cloud_firestore: ^5.6.5

  # Cloudinary
  cloudinary_public: ^0.23.1

  # Custom Repository
  user_repository:
    path: ../user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
